# Generated by Django 6.1.1 on 2026-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Escala'), ('chords', 'Círculo armónico')], max_length=10, verbose_name='modo')),
                ('config_key', models.CharField(db_index=True, help_text='Identifica tónica, escala y opciones; agrupa los intentos comparables.', max_length=120, verbose_name='configuración')),
                ('title', models.CharField(max_length=120, verbose_name='ejercicio')),
                ('accuracy', models.PositiveSmallIntegerField(verbose_name='precisión (%)')),
                ('errors', models.PositiveIntegerField(default=0, verbose_name='errores')),
                ('duration', models.FloatField(default=0, verbose_name='duración (s)')),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timing_ms', models.FloatField(blank=True, null=True, verbose_name='desvío medio (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'intento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(blank=True, help_text='Se muestra entre paréntesis en el selector, p. ej. «baja natural».', max_length=120, verbose_name='aclaración')),
                ('intervals', models.JSONField(help_text='Semitonos desde la tónica al subir, p. ej. [0, 2, 4, 5, 7, 9, 11].', verbose_name='intervalos')),
                ('descending', models.JSONField(blank=True, help_text='Solo si difieren de los de subida (menor melódica).', null=True, verbose_name='intervalos al bajar')),
                ('letters', models.JSONField(blank=True, help_text='Grado de letra (0–6) de cada nota. Vacío = una letra por nota (escalas de 7 notas).', null=True, verbose_name='grados de letra')),
                ('fingering', models.CharField(blank=True, choices=[('', 'Sin digitación'), ('major', 'Digitación de escala mayor (mano derecha)')], max_length=20, verbose_name='digitación')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'tipo de escala',
                'verbose_name_plural': 'tipos de escala',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_mode', models.CharField(choices=[('major', 'Mayor'), ('minor', 'Menor')], max_length=5, verbose_name='tonalidad')),
                ('code', models.CharField(help_text='Cifrado romano, p. ej. I-vi-IV-V.', max_length=40, verbose_name='código')),
                ('chords', models.JSONField(help_text='Lista de acordes: {"d": grado 0–6, "s": 1 si lleva séptima, "h": 1 si eleva la sensible}.', verbose_name='acordes')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'círculo armónico',
                'verbose_name_plural': 'círculos armónicos',
                'ordering': ['key_mode', 'order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('key_mode', 'code'), name='unique_progression_code')],
            },
        ),
    ]
