# Generated by Django 6.1.1 on 2026-09-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='lema')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'camino',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('practice', 'Escala'), ('chords', 'Círculo armónico'), ('module', 'Módulo')], max_length=10, verbose_name='modo'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='timing_ms',
            field=models.FloatField(blank=True, help_text='Escalas con metrónomo: desvío medio respecto al pulso. Módulos de lectura: tiempo medio por nota.', null=True, verbose_name='tiempo (ms)'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('summary', models.CharField(blank=True, max_length=240, verbose_name='resumen')),
                ('kind', models.CharField(choices=[('note_reading', 'Lectura de notas')], max_length=30, verbose_name='tipo de ejercicio')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Lectura de notas: {"clef": "treble", "low": 64, "high": 77, "naturals": true, "count": 15}', verbose_name='configuración')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='escalas.learningpath', verbose_name='camino')),
            ],
            options={
                'verbose_name': 'módulo',
                'ordering': ['path', 'order'],
            },
        ),
    ]
