# Generated by Django 6.1.1 on 2026-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0004_seed_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['path', 'level', 'order'], 'verbose_name': 'módulo'},
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], default=1, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='module',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Lectura de notas: {"clef": "treble|bass|mixed", "low": 64, "high": 77, "accidentals": false, "count": 15}. Lectura de frases: además "length" y "max_leap" (en grados). Acordes: {"chords": ["C", "Am", "G7"], "count": 12, "hints": "always|on_error"} o {"sequences": [{"name": "I–V–vi–IV en Do", "chords": ["C", "G", "Am", "F"]}], "laps": 2}.', verbose_name='configuración'),
        ),
        migrations.AlterField(
            model_name='module',
            name='kind',
            field=models.CharField(choices=[('note_reading', 'Lectura de notas'), ('melody_reading', 'Lectura de frases'), ('chord_play', 'Tocar acordes')], max_length=30, verbose_name='tipo de ejercicio'),
        ),
    ]
