# Generated by Django 6.1.1 on 2026-09-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0006_seed_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('composer', models.CharField(blank=True, max_length=120, verbose_name='compositor')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'canción',
                'verbose_name_plural': 'canciones',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='puntos'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('practice', 'Escala'), ('chords', 'Círculo armónico'), ('module', 'Módulo'), ('song', 'Canción')], max_length=10, verbose_name='modo'),
        ),
        migrations.CreateModel(
            name='SongArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], verbose_name='nivel')),
                ('title', models.CharField(help_text='P. ej. «Melodía y bajo».', max_length=120, verbose_name='título')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descripción')),
                ('tempo', models.PositiveSmallIntegerField(default=72, verbose_name='tempo (BPM)')),
                ('beats_per_bar', models.PositiveSmallIntegerField(default=4, verbose_name='tiempos por compás')),
                ('key_fifths', models.SmallIntegerField(default=0, help_text='Alteraciones de la armadura: negativo = bemoles, positivo = sostenidos.', verbose_name='armadura')),
                ('notes', models.JSONField(default=dict, help_text='{"rh": [[0, 1, 67], ...], "lh": [[0, 4, 43], ...]}', verbose_name='notas')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='escalas.song', verbose_name='canción')),
            ],
            options={
                'verbose_name': 'versión',
                'verbose_name_plural': 'versiones',
                'ordering': ['song', 'level'],
                'constraints': [models.UniqueConstraint(fields=('song', 'level'), name='unique_song_level')],
            },
        ),
    ]
