# Generated by Django 6.1.1 on 2026-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0009_basic_white_keys_maritza'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('clasica', 'Clásica'), ('cristiana', 'Cristiana'), ('popular', 'Popular')], default='clasica', max_length=20, verbose_name='categoría'),
        ),
    ]
