# Generated by Django 6.1.1 on 2026-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0012_attempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Partes de la canción: [{"name": "Coro", "from": 9, "to": 16}, ...] con compases desde 1. Se rellenan solas si el MIDI trae marcadores.', verbose_name='partes'),
        ),
    ]
