# Generated by Django 6.1.1 on 2026-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0013_song_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Encontrar teclas: {"notes": [60, 62, 64], "count": 12, "hints": "always|on_error|none", "fingers": [1, 2, 3], "exact": false, "any_octave": false}. Lectura de notas: {"clef": "treble|bass|mixed", "low": 64, "high": 77, "accidentals": false, "count": 15}. Lectura de frases: además "length" y "max_leap" (en grados). Acordes: {"chords": ["C", "Am", "G7"], "count": 12, "hints": "always|on_error"} o {"sequences": [{"name": "I–V–vi–IV en Do", "chords": ["C", "G", "Am", "F"]}], "laps": 2}.', verbose_name='configuración'),
        ),
        migrations.AlterField(
            model_name='module',
            name='kind',
            field=models.CharField(choices=[('key_finding', 'Encontrar teclas'), ('note_reading', 'Lectura de notas'), ('melody_reading', 'Lectura de frases'), ('chord_play', 'Tocar acordes')], max_length=30, verbose_name='tipo de ejercicio'),
        ),
    ]
