# Generated by Django 6.1.1 on 2026-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0015_seed_first_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='songarrangement',
            name='fingering',
            field=models.JSONField(blank=True, default=dict, help_text='Dedo (1 = pulgar … 5 = meñique) de cada nota, en el mismo orden: {"rh": [1, 2, ...], "lh": [...]}. Se calcula solo al importar; puedes corregirlo aquí.', verbose_name='dedos'),
        ),
    ]
