# Generated by Django 6.1.1 on 2026-09-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_view', models.CharField(choices=[('staff', 'Partitura'), ('rain', 'Lluvia de notas')], default='staff', help_text='Partitura: las notas en el pentagrama. Lluvia de notas: las notas caen hacia su tecla.', max_length=10, verbose_name='vista de las canciones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferencias',
                'verbose_name_plural': 'preferencias',
            },
        ),
    ]
