"""Textos del catálogo que viven en la base de datos (caminos, módulos, escalas, canciones incluidas).

Se guardan en español y se traducen al mostrarlos (filtro `tr` y `to_json`). Este archivo solo existe para que
`makemessages` los meta en el catálogo: no se importa. Si añades o cambias uno de estos textos en el admin, agrégalo aquí.
"""
from django.utils.translation import gettext_noop as _

_('Acompaña canciones con acordes.')
_('Acordes con sostenidos y bemoles')
_('Acordes de séptima')
_('Acordes de tensión y color para dar variedad a un acompañamiento.')
_('Acordes mayores')
_('Acordes menores')
_('Aprende a leer el pentagrama nota a nota, hasta tocar piezas escritas.')
_('Aprende acordes, inversiones y progresiones para tocar con otros músicos.')
_('Arpegios de dos octavas en corcheas y bajo en negras, con el final en acordes.')
_('Banda')
_('Blues de 12 compases')
_('Cada nota aparece en su clave, sol o fa, como en una partitura de piano. Cambia de lectura sin pausa.')
_('Canción de 1968 con derechos de autor vigentes: importa tu partitura en MIDI y la app crea las tres versiones.')
_('Clave de fa: las notas del pentagrama')
_('Clave de fa: líneas adicionales')
_('Clave de sol: las notas del pentagrama')
_('Clave de sol: líneas adicionales')
_('Con segunda voz y bajo arpegiado')
_('Del Do2 grave hasta el Mi4, que se escribe sobre el pentagrama de fa.')
_('Disminuidos, aumentados y suspendidos')
_('Do, Fa, Sol, Re, La y Mi: los acordes más usados en canciones. Verás sus notas en el teclado.')
_('Doxología')
_('Dórica')
_('El famoso bajo en ciclo de quintas de la Suite en sol menor HWV 432. Aprende primero la mano derecha, luego la izquierda y al final las dos juntas.')
_('El himno más cantado del mundo (Amazing Grace), en compás de tres.')
_('El sonido más oscuro: La menor, Re menor, Mi menor y compañía.')
_('El villancico de Navidad por excelencia, con su suave balanceo en tres.')
_('Encadena los tres acordes principales de una tonalidad, en Do y en Sol.')
_('Frases de ocho notas con saltos amplios y alteraciones en clave de sol.')
_('Frases de ocho notas para la mano izquierda, con saltos y alteraciones.')
_('Frases por grados conjuntos')
_('Frigia')
_('Generada automáticamente: la melodía y un bajo por medio compás.')
_('Generada automáticamente: teclas blancas, notas largas y una nota a la vez por mano.')
_('Himno de la alegría')
_('Interestelar')
_('La cadencia básica del jazz, con acordes de séptima, en Do, Fa, Si♭ y Mi♭.')
_('La clave de la mano izquierda: de Sol2 a La3, en líneas y espacios.')
_('La forma completa del blues con acordes de séptima, en Do y en Sol.')
_('La melodía completa con la fundamental de cada acorde en la izquierda.')
_('La melodía de la Novena sinfonía, cantada en iglesias como «Jubilosos te adoramos».')
_('La progresión de cientos de canciones, en cuatro tonalidades.')
_('La progresión pop: I–V–vi–IV')
_('Las dos claves alternadas')
_('Las mismas notas de la clave de sol, ahora con ♯ y ♭. Fíjate en la alteración antes de tocar.')
_('Lee frases cortas de cinco notas que se mueven por notas vecinas, como en una melodía.')
_('Lee partituras y toca música clásica.')
_('Lidia')
_('Locria')
_('Mayor')
_('Melodía en Do')
_('Menor armónica')
_('Menor melódica')
_('Menor natural')
_('Mixolidia')
_('Noche de paz')
_('Pentatónica mayor')
_('Pentatónica menor')
_('Primera vista en clave de fa')
_('Primera vista: saltos y alteraciones')
_('Reconoce las nueve notas que caen en las líneas y espacios, de Mi4 a Fa5, y tócalas en el piano.')
_('Segunda voz en los tiempos fuertes y bajo arpegiado en negras.')
_('Si♭, Mi♭, La♭, Fa♯ menor… Ahora las notas solo aparecen si te equivocas.')
_('Solista')
_('Solo teclas blancas: la melodía en notas largas y una nota de bajo por compás.')
_('Sostenidos y bemoles')
_('Sublime gracia')
_('Suma el Do central y las notas que se salen del pentagrama por arriba, hasta La5.')
_('Séptima de dominante, menor séptima y séptima mayor: el color del pop, el soul y el jazz.')
_('Tu primera progresión: I–IV–V')
_('baja natural')
_('ii–V–I en cuatro tonalidades')
_('«A Dios el Padre celestial»: el antiguo salmo 100, en notas largas y solemnes.')
_('Jean Renard y Pierre Delanoë (canta Sylvie Vartan)')
_('Melodía tradicional «New Britain» (1829)')
